import { useEffect, useState } from "react";
import { friendlyPlayerActionError } from "@/lib/player-action-errors";
import { postPlayerAction } from "@/lib/player-action-client";
import { formatClock } from "@/lib/team-style";
import { GameRulesChecklist } from "@/components/game-rules-ui";
import type { RoomState } from "@/lib/types";
import { TrackAudioPlayer } from "./TrackAudioPlayer";

export function TrackGuessPlayer({
  roomId,
  state,
  me,
}: {
  roomId: string;
  state: RoomState;
  me: { id: string; name: string; teamId: string };
}) {
  const tg = state.trackguess!;
  const [now, setNow] = useState(Date.now());
  const [pendingChoice, setPendingChoice] = useState<"real" | "ai" | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 500);
    return () => clearInterval(t);
  }, []);

  useEffect(() => {
    setPendingChoice(null);
    setActionError(null);
  }, [tg.phase, tg.roundNumber]);

  const myGuess = tg.guesses?.[me.id];

  async function guess(choice: "real" | "ai") {
    if (pendingChoice) return;
    setPendingChoice(choice);
    setActionError(null);
    try {
      await postPlayerAction(roomId, {
        action: "trackguess-guess",
        playerId: me.id,
        choice,
      });
    } catch (error) {
      setActionError(friendlyPlayerActionError(error, "guess"));
    } finally {
      setPendingChoice(null);
    }
  }

  if (tg.phase === "briefing") {
    return (
      <Card>
        <Pill>Warm up your ears</Pill>
        <H>Real or AI?</H>
        <P>
          A track is coming up. Listen closely — then pick: a live recording or one generated by AI.{" "}
          {tg.totalRounds} rounds, +2 points to team for a correct guess.
        </P>
        <GameRulesChecklist gameId="trackguess" />
      </Card>
    );
  }

  if (tg.phase === "listening") {
    const remaining = tg.listeningEndsAt ? Math.max(0, tg.listeningEndsAt - now) : null;
    return (
      <Card>
        <Pill>Round {tg.roundNumber}</Pill>
        <H>Listen closely</H>
        {remaining == null ? (
          <div className="mt-3 rounded-full bg-white/10 px-3 py-1 text-xs uppercase tracking-widest text-white/60">
            Host cueing
          </div>
        ) : (
          <div className="font-display text-4xl tabular-nums mt-2">{formatClock(remaining)}</div>
        )}
        <P>{tg.trackGenre}</P>
        {tg.trackUrl && (
          <TrackAudioPlayer
            src={tg.trackUrl}
            sourceUrl={tg.trackSourceUrl}
            audience="player"
            disabled={!!state.paused}
          />
        )}
        <P className="mt-3">
          {remaining == null
            ? "Wait for the host to start the track."
            : "No rush — voting opens soon."}
        </P>
      </Card>
    );
  }

  if (tg.phase === "guessing") {
    const remaining = Math.max(0, (tg.guessEndsAt ?? now) - now);
    if (myGuess) {
      return (
        <Card>
          <Pill>Vote locked in</Pill>
          <H>{myGuess === "ai" ? "🤖 AI" : "🎸 Real"}</H>
          <div className="text-right text-xs text-white/60 mt-1 tabular-nums">
            {formatClock(remaining)}
          </div>
          <P>Waiting on everyone else… The host will reveal the answer.</P>
        </Card>
      );
    }
    return (
      <div className="space-y-3">
        <Card compact>
          <Pill>
            Round {tg.roundNumber} · {formatClock(remaining)}
          </Pill>
          <H>Real or AI?</H>
          <P>{tg.trackGenre}</P>
        </Card>
        <button
          type="button"
          onClick={() => void guess("real")}
          disabled={!!pendingChoice}
          className="w-full rounded-3xl border border-[var(--color-park-bright)]/40 bg-[var(--color-park-bright)]/15 py-6 text-white"
        >
          <div className="text-3xl">🎸</div>
          <div className="font-display text-2xl mt-1">Real track</div>
          <div className="text-xs text-white/60 mt-1">
            {pendingChoice === "real" ? "Sending…" : "Live artist / studio"}
          </div>
        </button>
        <button
          type="button"
          onClick={() => void guess("ai")}
          disabled={!!pendingChoice}
          className="w-full rounded-3xl border border-violet-400/40 bg-violet-500/15 py-6 text-white"
        >
          <div className="text-3xl">🤖</div>
          <div className="font-display text-2xl mt-1">AI track</div>
          <div className="text-xs text-white/60 mt-1">
            {pendingChoice === "ai" ? "Sending…" : "Generated by AI"}
          </div>
        </button>
        {actionError && <ActionError>{actionError}</ActionError>}
      </div>
    );
  }

  if (tg.phase === "reveal" && typeof tg.isAi === "boolean") {
    const correct = myGuess != null && myGuess === (tg.isAi ? "ai" : "real");
    return (
      <Card>
        <Pill>{tg.isAi ? "🤖 AI" : "🎸 Real"}</Pill>
        <H>{tg.trackTitle}</H>
        {tg.trackArtist && <P>{tg.trackArtist}</P>}
        <div
          className={`mt-3 rounded-2xl px-4 py-3 text-center ${correct ? "bg-[var(--color-park-bright)]/20 text-[var(--color-park-bright)]" : "bg-white/10 text-white/80"}`}
        >
          {myGuess == null
            ? "You didn't vote in time"
            : correct
              ? "✓ Correct! +2 to team"
              : `✗ You picked ${myGuess === "ai" ? "AI" : "real"}`}
        </div>
      </Card>
    );
  }

  if (tg.phase === "results") {
    return (
      <Card>
        <Pill>Final</Pill>
        <H>Check the host screen</H>
        <P>Final leaderboard and track breakdown are up there.</P>
      </Card>
    );
  }

  return (
    <Card>
      <H>Hang tight…</H>
    </Card>
  );
}

function Card({ children, compact }: { children: React.ReactNode; compact?: boolean }) {
  return (
    <div
      className={`rounded-3xl bg-black/40 backdrop-blur border border-white/10 text-white ${compact ? "p-5" : "p-8 text-center"}`}
    >
      {children}
    </div>
  );
}

function Pill({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-xs uppercase tracking-widest text-[var(--color-park-bright)]">
      {children}
    </div>
  );
}

function H({ children }: { children: React.ReactNode }) {
  return <div className="font-display text-2xl mt-2">{children}</div>;
}

function P({ children, className }: { children: React.ReactNode; className?: string }) {
  return (
    <p className={`text-white/65 text-sm mt-2 leading-relaxed ${className ?? ""}`}>{children}</p>
  );
}

function ActionError({ children }: { children: React.ReactNode }) {
  return (
    <p className="rounded-2xl border border-red-300/20 bg-red-500/15 px-4 py-3 text-center text-sm text-red-100">
      {children}
    </p>
  );
}
